apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: guestbook-ui
          image: gcr.io/heptio-images/guestbook:v6
          ports:
            - containerPort: 80

